<html><body><h1>Closure Library Tests Results (Success: 2/5) - Took: 1085ms.</h1><table border="1"><tr>
<th>Test</th><th>Results</th><th>Summary</th><th>Details (Mouse Over for Code)</th>
<tr><td>mockcontrol_test</td><td>Fail</td><td> undefined</td><td>goog.require could not find: goog.testing.testing.asserts
Error: goog.require could not find: goog.testing.testing.asserts
    at Error (unknown source)
    at base.js:287:15
    at Object.intercept [as require] (/home/ubuntu/Dev/projects/node-goog/lib/googbase.js:144:7)
    at 2_mockcontrol_test.html.js:8:6
    at [object Object].loadTestContentsIntoMemory_ (/home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:181:9)
    at [object Object].run (/home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:143:8)
    at [object Object].runNextTestImpl_ (/home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:77:12)
    at [object Object].runNextTest_ (/home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:65:8)
    at [object Object].execute (/home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:49:8)
    at new <anonymous> (/home/ubuntu/Dev/projects/node-goog/bin/googtest.js:83:12)
</td></tr>
<tr><td>mockrandom_test</td><td>Success</td><td> 2 passed, 0 failed.</td><td>n/a</td></tr>
<tr><td>rendererasserts_test</td><td>Success</td><td> 2 passed, 0 failed.</td><td>n/a</td></tr>
<tr><td>mockclock_test</td><td>Fail</td><td> 5 passed, 11 failed.</td><td>16 of 16 tests run in 85ms.<br />5 passed, 11 failed.<br />5 ms/test. 1 files loaded.<br />ERROR in testClearInterval<br />Expected <5> (Number) but was <0> (Number)<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertEquals at testing/asserts.js:289:3<br />> testClearInterval at 5_mockclock_test.html.js:116:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testClearInterval2<br />Expected <5> (Number) but was <0> (Number)<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertEquals at testing/asserts.js:289:3<br />> testClearInterval2 at 5_mockclock_test.html.js:143:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testCorrectArgumentsPassedToCallback<br />The timeout was not executed<br />Call to assertTrue(boolean) with false<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertTrue at testing/asserts.js:261:3<br />> testCorrectArgumentsPassedToCallback at 5_mockclock_test.html.js:254:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testIsTimeoutSet<br />Timeout [object Object] should be set<br />Call to assertTrue(boolean) with false<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertTrue at testing/asserts.js:261:3<br />> testIsTimeoutSet at 5_mockclock_test.html.js:346:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testMockClockWasInstalled<br />Expected <1> (Number) but was <0> (Number)<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertEquals at testing/asserts.js:289:3<br />> testMockClockWasInstalled at 5_mockclock_test.html.js:15:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testMockGoogNow<br />Expected not to be <0> (Number)<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertNotEquals at testing/asserts.js:304:3<br />> testMockGoogNow at 5_mockclock_test.html.js:158:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testSetInterval<br />Expected <5> (Number) but was <0> (Number)<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertEquals at testing/asserts.js:289:3<br />> testSetInterval at 5_mockclock_test.html.js:83:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testSetTimeoutAndTick<br />Expected <4> (Number) but was <0> (Number)<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertEquals at testing/asserts.js:289:3<br />> testSetTimeoutAndTick at 5_mockclock_test.html.js:31:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testTickZero<br />Expected <2> (Number) but was <0> (Number)<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertEquals at testing/asserts.js:289:3<br />> testTickZero at 5_mockclock_test.html.js:275:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testTimeoutDelay<br />Call to assertTrue(boolean) with false<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertTrue at testing/asserts.js:261:3<br />> testTimeoutDelay at 5_mockclock_test.html.js:181:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in testTimerCallbackCanCreateIntermediateTimer<br />Each timer should fire in sequence at the correct time.<br />Expected <timer1 at T=1, timer2 at T=2, timer3 at T=3> (String) but was <> (String)<br />> Object.get at testing/stacktrace.js:462:15<br />> new &lt;anonymous&gt; at testing/asserts.js:931:45<br />> Object.raiseException_ at testing/asserts.js:905:9<br />> _assert at testing/asserts.js:145:26<br />> assertEquals at testing/asserts.js:289:3<br />> testTimerCallbackCanCreateIntermediateTimer at 5_mockclock_test.html.js:228:5<br />> [object Object].execute at testing/testcase.js:901:12<br />> [object Object].cycleTests at testing/testcase.js:691:16<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />ERROR in 5_mockclock_test.html.js<br />ERROR: Test did not restore setTimeout<br /></td></tr>
<tr><td>expectedfailures_test</td><td>Fail</td><td> 0 passed, 7 failed.</td><td>7 of 7 tests run in 34ms.<br />0 passed, 7 failed.<br />5 ms/test. 1 files loaded.<br />ERROR in testDoNotPreventException<br />document is not defined<br />> Object.&lt;anonymous&gt; at dom/dom.js:641:14<br />> Function.setUpConsole_ at testing/expectedfailures.js:115:28<br />> new &lt;anonymous&gt; at testing/expectedfailures.js:63:33<br />> [object Object].setUp at 3_expectedfailures_test.html.js:18:24<br />> [object Object].cycleTests at testing/testcase.js:690:12<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />> [object Object].createAndRunTestCase_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:194:18<br />> [object Object].run at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:144:8<br />> [object Object].runNextTestImpl_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:77:12<br />ERROR in testExpectedFailureDidNotOccur<br />document is not defined<br />> Object.&lt;anonymous&gt; at dom/dom.js:641:14<br />> Function.setUpConsole_ at testing/expectedfailures.js:115:28<br />> new &lt;anonymous&gt; at testing/expectedfailures.js:63:33<br />> [object Object].setUp at 3_expectedfailures_test.html.js:18:24<br />> [object Object].cycleTests at testing/testcase.js:690:12<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />> [object Object].createAndRunTestCase_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:194:18<br />> [object Object].run at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:144:8<br />> [object Object].runNextTestImpl_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:77:12<br />ERROR in testNoExpectedFailure<br />document is not defined<br />> Object.&lt;anonymous&gt; at dom/dom.js:641:14<br />> Function.setUpConsole_ at testing/expectedfailures.js:115:28<br />> new &lt;anonymous&gt; at testing/expectedfailures.js:63:33<br />> [object Object].setUp at 3_expectedfailures_test.html.js:18:24<br />> [object Object].cycleTests at testing/testcase.js:690:12<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />> [object Object].createAndRunTestCase_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:194:18<br />> [object Object].run at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:144:8<br />> [object Object].runNextTestImpl_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:77:12<br />ERROR in testPreventExpectedFailure<br />document is not defined<br />> Object.&lt;anonymous&gt; at dom/dom.js:641:14<br />> Function.setUpConsole_ at testing/expectedfailures.js:115:28<br />> new &lt;anonymous&gt; at testing/expectedfailures.js:63:33<br />> [object Object].setUp at 3_expectedfailures_test.html.js:18:24<br />> [object Object].cycleTests at testing/testcase.js:690:12<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />> [object Object].createAndRunTestCase_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:194:18<br />> [object Object].run at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:144:8<br />> [object Object].runNextTestImpl_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:77:12<br />ERROR in testRun<br />document is not defined<br />> Object.&lt;anonymous&gt; at dom/dom.js:641:14<br />> Function.setUpConsole_ at testing/expectedfailures.js:115:28<br />> new &lt;anonymous&gt; at testing/expectedfailures.js:63:33<br />> [object Object].setUp at 3_expectedfailures_test.html.js:18:24<br />> [object Object].cycleTests at testing/testcase.js:690:12<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />> [object Object].createAndRunTestCase_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:194:18<br />> [object Object].run at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:144:8<br />> [object Object].runNextTestImpl_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:77:12<br />ERROR in testRunLenient<br />document is not defined<br />> Object.&lt;anonymous&gt; at dom/dom.js:641:14<br />> Function.setUpConsole_ at testing/expectedfailures.js:115:28<br />> new &lt;anonymous&gt; at testing/expectedfailures.js:63:33<br />> [object Object].setUp at 3_expectedfailures_test.html.js:18:24<br />> [object Object].cycleTests at testing/testcase.js:690:12<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />> [object Object].createAndRunTestCase_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:194:18<br />> [object Object].run at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:144:8<br />> [object Object].runNextTestImpl_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:77:12<br />ERROR in testRunStrict<br />document is not defined<br />> Object.&lt;anonymous&gt; at dom/dom.js:641:14<br />> Function.setUpConsole_ at testing/expectedfailures.js:115:28<br />> new &lt;anonymous&gt; at testing/expectedfailures.js:63:33<br />> [object Object].setUp at 3_expectedfailures_test.html.js:18:24<br />> [object Object].cycleTests at testing/testcase.js:690:12<br />> [object Object].execute at testing/testcase.js:346:8<br />> [object Object].runTests at testing/testcase.js:489:8<br />> [object Object].createAndRunTestCase_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:194:18<br />> [object Object].run at /home/ubuntu/Dev/projects/node-goog/bin/nodetestinstance.js:144:8<br />> [object Object].runNextTestImpl_ at /home/ubuntu/Dev/projects/node-goog/bin/nodetestsrunner.js:77:12<br /></td></tr></table></body></html>